# SWAML Makefile

DESTDIR =

install:
	echo unavailable

uninstall:
	echo unavailable

test:
	echo unavailable

clean:
	rm -rf archive/
	rm -f *~
	rm -f classes/*.pyc
	rm -f classes/*~
	rm -f templates/*~
