   <rdf:msg>
    <msg:From>{FROM}</msg:From>
    <msg:To>{TO}</msg:To>
    <msg:Subject>{SUBJECT}</msg:Subject>
    <msg:Date>{DATE}</msg:Date>
    <msg:MessageId>{MESSAGE_ID}</msg:MessageId>
    <msg:RdfURL>{RDF_URL}</msg:RdfURL>
    <msg:HtmlURL>{HTML_URL}</msg:HtmlURL>
    <msg:InReplyTo>{IN_REPLY_TO}</msg:InReplyTo>
    <msg:Body>{BODY}</msg:Body>
   <rdf:msg>
