   <rdf:swaml>
    <swaml:From>
     <foaf:Person>
      <foaf:fullname>{FROM_NAME}</foaf:fullname>
      <foaf:mbox_sha1sum>{FROM_MBOX}</foaf:mbox_sha1sum>
     </foaf:Person>
    </swaml:From>
    <swaml:To>{TO}</swaml:To>
    <swaml:Subject>{SUBJECT}</swaml:Subject>
    <swaml:Date>{DATE}</swaml:Date>
    <swaml:MessageId>{MESSAGE_ID}</swaml:MessageId>
    <swaml:RdfURL>{RDF_URL}</swaml:RdfURL>
    <swaml:HtmlURL>{HTML_URL}</swaml:HtmlURL>
    <swaml:InReplyTo>{IN_REPLY_TO}</swaml:InReplyTo>
    <swaml:Body>
     {BODY}
    </swaml:Body>
   </rdf:swaml>
