   <swaml:item>
    <swaml:From>
     <foaf:Person>
      <foaf:fullname>{FROM_NAME}</foaf:fullname>
      <foaf:mbox_sha1sum>{FROM_MBOX}</foaf:mbox_sha1sum>
     </foaf:Person>
    </swaml:From>
    <swaml:Subject>{SUBJECT}</swaml:Subject>
    <swaml:MessageId>{MESSAGE_ID}</swaml:MessageId>
    <swaml:RdfURL>{RDF_URL}</swaml:RdfURL>
   </swaml:item>
