.TH SWAML "1" "December 2006" "swaml" "User Commands"
.SH NAME
\fBSWAML\fP \- Semantic Web Archive of Mailing Lists
.SH SYNOPSIS
\fBswaml\fP \fIconfigfile\fP [options]
.SH DESCRIPTION
\fBswaml\fP transform the archives of a mailing list (in mbox format)
into a semantic web friendly format (RDF in XML).
.SH OPTIONS
.TP
.B
\fB\-h\fR, \fB\-\-help\fR
Print help text and exit.
.TP
.B
\fB\-V, --version\fP
Print version and exit.
.TP
.B
\fB\-v, --verbose\fP
Turn on verbose mode.
.SH AUTHOR
Manpage written by Nacho Barrientos Arias <chipi@criptonita.com> for the Debian GNU/Linux system (but may be used by others).
.SH BUGS
Report bugs to Debian BTS or to http://swaml.berlios.de/bugs.
.SH COPYRIGHT
Copyright \(co 2006, Sergio Fdez. Licensed under GPLv2 license.
.PP
.nf
.fam C
http://swaml.berlios.de/
